Hw 10
ISkalchenkov/2022-2-VK-EDU-FS-Frontend-I-Skalchenkov pull request #10
Opened 2023-01-08 11:36 UTC by ISkalchenkov

# Домашнее задание №10

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* Реализована страница авторизации и интегрирована с бэкэндом (провайдер OAuth - Google);
* Пользователь не может попасть ни на какую внутреннюю страницу, кроме страницы авторизации;
* Авторизованный пользователь не может попасть на страницу авторизации без предварительного выхода;
* Реализовано выпадающее меню, появляющееся при нажатии на кнопку "бургер"; в выпадающем меню появляется возможность перейти в профиль пользователя или выполнить логаут.
### Демонстрационное видео
[![Watch the video](https://img.youtube.com/vi/LwnXYwlwORs/maxresdefault.jpg)](https://youtu.be/LwnXYwlwORs)

2023-01-08 14:43 UTC, martinkomitsky commented on react-chat/src/App.js
> +    }
почему не фетч?

2023-01-08 15:44 UTC, martinkomitsky commented on react-chat/src/App.js
> +function if_allowed(Page) {
Сейчас запрос выполняется `n` раз, это очень плохо. А ещё, он будет выполняться на каждый рендер

2023-01-08 15:45 UTC, martinkomitsky requested changes
Исправить замечания

2023-01-09 03:28 UTC, ISkalchenkov commented on react-chat/src/App.js
> +    }
Использовал XMLHttpRequest, чтобы сделать функцию синхронной и чтобы проверка на авторизованного пользователя срабатывала до завершения рендера. Сейчас переписал данную проверку на fetch, теперь она вызывается при монтировании приложения и результат записывается в state. Поскольку после выполнения componentDidMount результат первого рендера отображается на экране, и лишь потом изменение state'а триггерит второй рендер приложения, то при открытии мессенджера авторизованным пользователем страница с авторизацией успевает отобразиться на небольшое время. Для устранения данной неприятности сделано так, что первый рендер возвращает null (пустой экран). Не знаю, можно ли решить данную проблему каким-то более удобным способом

2023-01-09 10:20 UTC, martinkomitsky commented on react-chat/src/App.js
> +    }
так обычно и делают. Либо на время загрузки делают прелоадер

2023-01-09 10:20 UTC, martinkomitsky approved these changes
7

2023-01-09 10:20 UTC, merged